acme_issuer letsencrypt {
    uri https://acme-v02.api.letsencrypt.org/directory;
    state_path /var/cache/nginx/acme/state;
    account_key ecdsa:384;
    challenge http-01;
    accept_terms_of_service;
}
acme_shared_zone zone=ngx_acme_shared:1M;
